data:
  raw_data_path: "data/raw/complete_dataset.csv"
  processed_data_path: "data/processed/"

preprocessing:
  test_size: 0.2
  validation_size: 0.2
  random_state: 42

models:
  random_forest:
    n_estimators: 100
    max_depth: null
    random_state: 42

  lstm:
    epochs: 50
    batch_size: 32
    lstm_units: 50

forecasting:
  forecast_horizon: 30  # days

paths:
  models: "models/saved_models/"
  results: "results/"
  figures: "results/figures/" 